# Generated by Django 6.0.2 on 2026-02-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='allowed_courses',
            field=models.JSONField(blank=True, default=list, help_text="List of course codes (e.g. ['TU856', 'TU123']) that are allowed to enroll in this module. Leave empty for no restrictions."),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, help_text='Course Code & Name (e.g. TU856 - BSc in Computer Science)', max_length=64, null=True),
        ),
    ]
