# Generated by Django 6.0.2 on 2026-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_module_allowed_courses_studentprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='allowed_courses',
            field=models.CharField(blank=True, help_text="List of course codes (e.g. ['TU856', 'TU123']) that are allowed to enroll in this module. Leave empty for no restrictions.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, help_text='Course Code(e.g. TU856 - No Name Included)', max_length=10, null=True),
        ),
    ]
