# Generated by Django 6.0.2 on 2026-03-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_module_allowed_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='academic_year_start',
        ),
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
        migrations.AddField(
            model_name='module',
            name='end_date',
            field=models.DateField(blank=True, help_text='Module end date (month/day used; can be before start for Sep→May style modules).', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='last_rollover_year',
            field=models.PositiveIntegerField(default=0, help_text='The start-year of the most recent rollover cycle (e.g. 2025).'),
        ),
        migrations.AddField(
            model_name='module',
            name='start_date',
            field=models.DateField(blank=True, help_text='Module start date (month/day used for annual rollover).', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='allowed_courses',
            field=models.JSONField(blank=True, default=list, help_text="List of course codes allowed to enroll (e.g. ['TU856','DT228']). Empty = no restriction."),
        ),
    ]
