# Generated by Django 6.0.2 on 2026-03-06 17:52

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_module_academic_year_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_extension', models.CharField(max_length=10)),
                ('parser_status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('parsed_blocks', models.JSONField(blank=True, default=list)),
                ('rendered_html', models.TextField(blank=True)),
                ('parse_error', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_document', to='accounts.assignmentfile')),
                ('week_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_document', to='accounts.moduleweekfile')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedDocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=apps.accounts.models.parsed_document_image_upload_path)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.parseddocument')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('parsed_document', 'token')},
            },
        ),
    ]
