# Generated by Django 6.0.2 on 2026-03-10 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_quiz_quizattempt_quizquestion_quizoption_quizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('ASSIGNMENT_NEW', 'New assignment'), ('ASSIGNMENT_DUE_3D', 'Assignment due in 3 days'), ('ASSIGNMENT_DUE_24H', 'Assignment due in 24 hours'), ('ASSIGNMENT_SUBMITTED', 'Assignment submitted'), ('ASSIGNMENT_GRADED', 'Assignment graded'), ('ASSIGNMENT_CLOSED_SUMMARY', 'Assignment closed summary'), ('ASSIGNMENT_GRADING_REMINDER', 'Assignment grading reminder'), ('QUIZ_NEW', 'New quiz'), ('QUIZ_OPENED', 'Quiz opened'), ('QUIZ_CLOSED', 'Quiz closed'), ('QUIZ_SUBMITTED', 'Quiz submitted'), ('QUIZ_CLOSED_SUMMARY', 'Quiz closed summary'), ('WEEK_AVAILABLE', 'New week available'), ('PARSER_SUCCESS', 'Parser success'), ('PARSER_FAILURE', 'Parser failure')], default='GENERAL', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('redirect_url', models.CharField(blank=True, max_length=500)),
                ('event_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.module')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_key'), name='unique_notification_event_per_user')],
            },
        ),
    ]
