# Generated by Django 6.0.2 on 2026-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_globalannouncement_moduleannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colour_scheme',
            field=models.CharField(choices=[('default', 'Default'), ('protanopia', 'Protanopia'), ('deuteranopia', 'Deuteranopia'), ('tritanopia', 'Tritanopia'), ('achromatopsia', 'Achromatopsia'), ('high-contrast', 'High Contrast')], default='default', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='font_scheme',
            field=models.CharField(choices=[('default', 'Default'), ('open-dyslexic', 'Open Dyslexic'), ('atkinson-hyperlegible', 'Atkinson Hyperlegible')], default='default', max_length=32),
        ),
    ]
