# Generated by Django 5.2.8 on 2025-11-15 04:29

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_assignment_module_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='accounts.module')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('module', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='ModuleWeekFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.module_week_file_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.moduleweek')),
            ],
        ),
    ]
